name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch: #posso executar na mão
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção da Imagem Docker
        run: echo "Executando o comando docker push"

#O certo é depois da construção fazer uma verificação
#de vulnerabilidade primeiro, mas nesse passo não está fazendo
      -
        name: Construção da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: | # Utilizar para colocar mais de 1 tag
            luuucasmoreia/fake-shop:latest
            luuucasmoreia/fake-shop:v${{ github.run_number }}
          #essa espressão deixa a numeração da versão como auto-increment   
                   

  cd:
    runs-on: ubuntu-24.04
    needs: [ci] #dependendo do ci completar primeiro
    permissions: #requisitos da action para deploy do kubernets
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Configurar o kubectl
        run: aws eks update-kubeconfig --name aula-k8s
      
      - name: Deploy dos manifestos no kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            luuucasmoreia/fake-shop:v${{ github.run_number }}