name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch: #posso executar na mão
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3

      - name: Construção da Imagem Docker
        run: echo "Executando o comando docker push"

  cd:
    runs-on: ubuntu-latest
    needs: [ci] #dependendo do ci completar primeiro
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando aws configure"
      - name: configurar o kubeconfig
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Deploy do manifesto
        run: echo "Executando o comando kubectl apply"
