name: CI-CD

on:
  push:
    branches: ["k8s-local"]
  workflow_dispatch: #posso executar na mão
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção da Imagem Docker
        run: echo "Executando o comando docker push"

#O certo é depois da construção fazer uma verificação
#de vulnerabilidade primeiro, mas nesse passo não está fazendo
      # -
      #   name: Construção da Imagem Docker
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./src
      #     push: true
      #     file: ./src/Dockerfile
      #     tags: | # Utilizar para colocar mais de 1 tag
      #       luuucasmoreia/fake-shop:latest
      #       luuucasmoreia/fake-shop:v${{ github.run_number }}
          #essa espressão deixa a numeração da versão como auto-increment   
                   

  cd:
    runs-on: ubuntu-24.04
    needs: [ci] #dependendo do ci completar primeiro
    permissions: #requisitos da action para deploy do kubernets
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start
      
      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml

      - name: Get Minikube IP
        id: minikube-ip
        run: |
          echo "IP=$(minikube ip)" >> $GITHUB_ENV

      - name: Instalar ngrok #para expor o serviço no github action
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && \
          sudo apt-get update && sudo apt-get install ngrok
  
      - name: Expor serviço via ngrok
        id: expose-ngrok
        run: |
          nohup ngrok http $(minikube ip):30000 &
          sleep 5
          echo "NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')" >> $GITHUB_ENV
      
      - name: Print Access Info
        run: |
          echo "Aplicação disponível em: http://${{ env.IP }}:30000"
          echo "O job será finalizado em 5 minutos. Acesse a aplicação agora!"

      - name: Delay for 5 minutes
        run: |
          sleep 300  # 300 segundos = 5 minutos

      - name: Clean up
        run: |
          minikube delete